version: "3"

services:
  project_db:
    container_name: project_db
    image: mysql:5.7
    environment:
      MYSQL_DATABASE: project
      MYSQL_USER: root
      MYSQL_PASSWORD: 12345678
    ports: 
      - "3306:3306"
      
  project:
    container_name: project
    image: project
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    depends_on:
       - project_db
  
