version: "3"
    
services:
  project_db:
    image: mysql:5.7
    volumes:
      - ./data:/var/lib/mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 12345678
      MYSQL_DATABASE: project
      MYSQL_USER: admin
      MYSQL_PASSWORD: password
    ports: 
      - "3307:3307"
